### ISSUE TITLE
Accueil

### ISSUE THREAD

**Issue by paulgirard** [medialab/respadon-website#1]
Design: [accueil.pdf](https://github.com/medialab/respadon-website/files/9190301/accueil.pdf)
Contenu: https://docs.google.com/document/d/1DL14fTN6fLuD2qxSk5GjT-P0xR10WdQYj-iP_dBDQaU/

/!\ les encarts sont spécifiques à cette page pas la peine de les rendre générique

En plus des contenus il faut ajouter : 
- [x] Image/titre avec fonction plein écran
- [x] #3
- [x] #4
- [x] #5

**Comment by paulgirard** [comment]
Il manque les textes des encarts stories, méthodologie et Making-of

**Comment by jacomyal** [comment]
Les intégrations sont faites, il ne reste qu'à remplacer les Lorem ipsum qui restent par les bons contenus quand ça sera possible.
