### ISSUE TITLE
Diverses améliorations suite réu 30/09

### ISSUE THREAD

**Issue by paulgirard** [medialab/respadon-website#11]
- [x] Ajouter un titre à la page Stories
- [x] Mettre à jour les titre et textes des stories dans les stories de la home
- [x] Préparer une intégration dans la story Politique d'une note sous forme de tooltips avec un lien dedans
- [ ] Réduire la largeur des paragraphes trop larges dans les pages statiques
- [x] Préparer une intégration image + iframe en fullscreen
- [x] Préparer une intégration de lien de téléchargement des données d'un graphique en plein écran
- [x] Session d'une heure avec Émilie pour les callages graphiques dont le carrousel photo de la home
- [x] Intégrer les dernières modifications dans la page contexte
- [x] adresse email dans le footer

**Comment by jacomyal** [comment]
- L'exemple de note est dans la story "Politique", avec un texte qui commence par `L’analyse comparative de ces trois corpus...`
```
          <Note>          
              <>          
                L’analyse comparative de ces trois corpus nécessite d’expérimenter de nouvelles
                formes de représentation graphique non disponibles dans Hyphe ou dans des outils
                traditionnels.
              </>         
              <>          
                Visualisations dynamiques de réseaux disponibles en ligne via l'outil Nansi :
                <ul>      
                  <li>    
                    <a href="https://medialab.github.io/nansi/?graph=https%3A%2F%2Fraw.githubusercontent.com%2Fmedialab%2Frespadon-datasprint-2022%2Fmaster%2Fcommunautes_politiques%2Fdata%2Fmelenchon_2012.gexf">
                      corpus 2012
                    </a>  
                  </li>   
                  <li>    
                    <a href="https://medialab.github.io/nansi/?graph=https%3A%2F%2Fraw.githubusercontent.com%2Fmedialab%2Frespadon-datasprint-2022%2Fmaster%2Fcommunautes_politiques%2Fdata%2Fmelenchon_2017.gexf">
                      corpus 2017
                    </a>  
                  </li>   
                  <li>    
                    <a href="https://medialab.github.io/nansi/?graph=https%3A%2F%2Fraw.githubusercontent.com%2Fmedialab%2Frespadon-datasprint-2022%2Fmaster%2Fcommunautes_politiques%2Fdata%2Fmelenchon_2022.gexf">
                      corpus 2022
                    </a>  
                  </li>   
                </ul>     
              </>         
            </Note>    
```

- L'exemple d'iframe est accessible en cliquant sur l'image `Répartition des web entités par forme éditoriale / en 2022` dans la story "Politique"
- L'exemple de lien de téléchargement des données est dispo en cliquant sur l'image `Évolution du nombre de pages web crawlées et détectées et des liens trouvés dans les 3 corpus en 2012, 2017 et 2022`
