### ISSUE TITLE
Schéma story Covid à refaire

### ISSUE THREAD

**Issue by audreybaneyx** [medialab/respadon-website#20]
Refaire le schéma méthodo en enlevant le petit "capture d'écran" qui apparait en haut à gauche ...

**Comment by audreybaneyx** [comment]
done ! : fichier modifiable ici pour mémoire => https://drive.google.com/drive/folders/1BcoSlXQPr-f53mINOfNoJmm-Vfy2N51-?usp=share_link
Fichier jpg mis en ligne sur github et appel changé dans le code source de la story

**Comment by boogheta** [comment]
:+1:
