### ISSUE TITLE
[Story COVID] Refaire screenshot "Représentation des graphes"

### ISSUE THREAD

**Issue by boogheta** [medialab/respadon-website#28]
il y a un rectangle vert par dessus

**Comment by audreybaneyx** [comment]
Je ne vois pas le rectangle vert sur mon écran @boogheta ...

**Comment by boogheta** [comment]
il est plutôt jaune en fait, à cheval sur 2020 et 2021 sur cette image : 
https://respadon.medialab.sciencespo.fr/pictures/story-covid/networks_2020_2021_2022_acteurs.png
![image](https://user-images.githubusercontent.com/1822297/212934256-08b64a62-4068-4be4-ae2e-84de6a2dbf49.png)
